/*
 * 6-3
 * Using the SASHELP data set Heart, test if the mean weight is equal to
 * 150. Include a test for normality and make sure that the defualt plots
 * are selected. Can you explain why the test is so highly significant
 * when the mean weight is 153.1? 
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/9/17, 6:02 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

/*** Test for normality ***/
proc univariate data=SASHELP.HEART normal mu0=150;
	ods select TestsForNormality;
	var Weight;
run;

/*** t Test ***/
proc ttest data=SASHELP.HEART sides=2 h0=150 plots(showh0);
	var Weight;
run;

# The low p-value result is from the large sample size (N = 5203).
