/*
 * 12-3
 * Starting with the CSV file Risk.csv, create a temporary SAS data set
 * (call it Risk). Use the binary logistic regression task to predict a
 * heart attack (variable Heart_Attack, 1=yes, 0=no) with the two risk
 * factors Age_Group (less than 60, 61 to 70, and 71 and older) and 
 * Chol_High (1=yes, 0=mo). Use reference coding.
 */

/* Generated Code (IMPORT) */
/* Source File: Risk.csv */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/24/17, 9:10 PM */

%web_drop_table(WORK.Risk);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Risk.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=WORK.Risk;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Risk; RUN;


%web_open_table(WORK.Risk);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/24/17, 9:17 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc logistic data=WORK.RISK;
	class Age_Group Chol_High / param=ref;
	model Heart_Attack(event='1')=Age_Group Chol_High / link=logit 
		technique=fisher;
run;