/*
 * 13-1
 * Starting with the file Risk.csv, use the import utility to create a
 * temporary SAS data set called Risk. Use the one-way Frequencies task 
 * to create one-way frequencies for the variables Age_Group, Chol_High,
 * Gender, and Heart_Attack. Use the appropriate options to omit plots
 * and to omit cumulative frequencies and percentages. 
 */

/* Generated Code (IMPORT) */
/* Source File: Risk.csv */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/25/17, 6:48 PM */

%web_drop_table(WORK.Risk);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Risk.csv';

PROC IMPORT DATAFILE=REFFILE
	DBMS=CSV
	OUT=WORK.Risk;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Risk; RUN;


%web_open_table(WORK.Risk);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/25/17, 6:51 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

proc freq data=WORK.RISK;
	tables Age_Group Gender Chol_High Heart_Attack / nocum plots=none;
run;