/*
 * 13-2
 * Using the Risk data set, construct a 2x2 table with the variable
 * Chol_High on the row dimension and Heart_Attack on the column dimension.
 * Include a calculation of the chi-square, odds ratio and relative risk.
 * Omit all plots.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/25/17, 6:55 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;

proc freq data=WORK.RISK;
	tables  (Chol_High) *(Heart_Attack) / chisq relrisk nopercent norow nocol 
		nocum plots=none;
run;