/*
 * 13-4
 * Create an excel worksheet of the table shown. Then create a SAS data
 * set and compute chi-square for the table. What is the odds ratio for
 * the risk factor = 1?
 */

/* Generated Code (IMPORT) */
/* Source File: DataTable13-4.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/other_data */
/* Code generated on: 9/25/17, 7:19 PM */

%web_drop_table(WORK.RiskFactor13_4);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/other_data/DataTable13-4.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.RiskFactor13_4;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.RiskFactor13_4; RUN;


%web_open_table(WORK.RiskFactor13_4);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/25/17, 7:24 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;

proc freq data=WORK.RISKFACTOR13_4;
	tables  (Outcome) *(Risk_Factor) / chisq relrisk nopercent norow nocol nocum 
		plots=none;
	weight Count;
run;



