/*
 * 14-3
 * Compute the sample size per group for the following study:
 * ANOVA
 * Two-tailed
 * Alpha = 0.05
 * Mean of group 1: 50
 * Mean of group 2: 60
 * Mean of group 3: 70
 * Estimated pooled standard deviation: 10
 * Powers: 80% and 90%
 */


/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '10/1/17, 5:32 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc power ;
	onewayanova test=overall groupmeans=(50 60 70) stddev=10 power=0.8 0.9 
		alpha=0.05 npergroup=.;
	plot x=power;
run;
