/*
 * 6-1
 * Using the workbook Diabetes.xls, create a temporary SAS data set called 
 * Diabetes. Next, conduct a one-sample t-test with the null hypothesis
 * of Glucose = 200 (alt Hypothesis Glucose not equal to 200). Include
 * tests for normality and nonparametric tests.  
 */

/* Generated Code (IMPORT) */
/* Source File: Diabetes.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/9/17, 5:28 PM */

%web_drop_table(WORK.Diabetes);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Diabetes.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.Diabetes;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Diabetes; RUN;


%web_open_table(WORK.Diabetes);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/9/17, 5:30 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

/*** Test for normality ***/
proc univariate data=WORK.DIABETES normal mu0=200;
	ods select TestsForNormality;
	var Glucose;
run;

/*** t Test ***/
proc ttest data=WORK.DIABETES sides=2 h0=200 plots(showh0);
	var Glucose;
run;

/*** Nonparametric test ***/
proc univariate data=WORK.DIABETES mu0=200;
	ods select TestsForLocation;
	var Glucose;
run;

/* All tests fail to reject the null.
 * Tests for normality also fail to reject the null that Glucose values
 * are normally distributed
*/