/*
 * 6-2
 * Using the SASHELP data set Fish, test if the mean  weight of perch is
 * equal to 500. Include test for normality as well as histograms and
 * Q-Q plots. After looking at these tests and plots, rerun the t-test 
 * task requesting a Wilcoxon Rank sum test.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/9/17, 5:55 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

/*** Test for normality ***/
proc univariate data=SASHELP.FISH normal mu0=150;
	ods select TestsForNormality;
	where Species='Perch';
	var Weight;
run;

/*** t Test ***/
proc ttest data=SASHELP.FISH sides=2 h0=150 plots(only showh0)=(summaryPlot 
		qqplot);
	where Species='Perch';
	var Weight;
run;

/*** Nonparametric test ***/
proc univariate data=SASHELP.FISH mu0=150;
	ods select TestsForLocation;
	where Species='Perch';
	var Weight;
run;