/*
 * 9-1
 * Using the Blood_Pressure.xlsx workbook, create a temporary SAS data set
 * (call it BP). Run a two-way ANOVA model with DBP ass the dependent 
 * variable with Drug and Gender as factors. Run a full factorial model.
 * Be sure to check the interaction term before interpreting the main effects.
 * Include diagostic plots in your output. Using the Tukey method, determine
 * which Drug groups are different (if any). 
 */

/* Generated Code (IMPORT) */
/* Source File: Blood_Pressure.xlsx */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/18/17, 6:17 PM */

%web_drop_table(WORK.BP);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Blood_Pressure.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.BP;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.BP; RUN;


%web_open_table(WORK.BP);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/18/17, 6:21 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glm data=WORK.BP plot(only)=(diagnostics intplot);
	class Drug Gender;
	model DBP=Drug Gender Drug*Gender / ss1 ss3;
	lsmeans Drug Gender / adjust=tukey pdiff=all alpha=0.05 cl plots=(meanplot(cl) 
		diffplot);
quit;

/*
 * The interaction term was not significant. Drug was was significantly different at 
 * 0.05 level. The Tukey comparison shows that Drug B and placebo are signicantly
 * different (p=0.0137).
 */