/*
 * 9-4
 * Rerun problem 9-3 but without the group Diet_Drinks = 'Sometimes'.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/18/17, 7:19 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glm data=WORK.DIABETES plot(only)=(intplot);
	where Diet_Drinks ne 'Sometimes';
	class Insulin Diet_Drinks;
	model Glucose=Insulin Diet_Drinks Insulin*Diet_Drinks / ss1 ss3;
	lsmeans Insulin Diet_Drinks Insulin*Diet_Drinks / adjust=tukey pdiff=all 
		alpha=0.05 cl plots=(meanplot(cl) diffplot);
quit;