/*
 * 9-3
 * Using the workbook Diabetes.xls, create a temporary SAS data set (call
 * it Diabetes) and perform a two-way ANOVA with Glucose as the dependent
 * variable and Insulin and Diet_Drinks as factors (independent) variables.
 * Be sure to check interaction term before main effects. Request multiple
 * comparison for all effects as well as an interaction plot.
 */

/* Generated Code (IMPORT) */
/* Source File: Diabetes.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/18/17, 7:05 PM */

%web_drop_table(WORK.Diabetes);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Diabetes.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.Diabetes;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Diabetes; RUN;


%web_open_table(WORK.Diabetes);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/18/17, 7:09 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glm data=WORK.DIABETES plot(only)=(intplot);
	class Insulin Diet_Drinks;
	model Glucose=Insulin Diet_Drinks Insulin*Diet_Drinks / ss1 ss3;
	lsmeans Insulin Diet_Drinks Insulin*Diet_Drinks / adjust=tukey pdiff=all 
		alpha=0.05 cl plots=(meanplot(cl) diffplot);
quit;

/*
 * The interaction term is signicant (p=0.0288). The multiple Comparisons
 * from the Tukey-Kramer output shows the pairwise combinations that are sig
 * different (with p-vals < 0.05).
 */