/*
 * 9-2
 * Using the SASHELP data set HEART, run a two-way ANOVA using Weight 
 * as the dependent variable and Sex and Chol_Status (cholesterol status)
 * as factors. Request multiple comparisons for main effects and 
 * Type 3 sum of squares only. Suppress all plots. What comparisons are 
 * signicant for Chol_Status?   
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/18/17, 6:45 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glm data=SASHELP.HEART plots=none;
	class Sex Chol_Status;
	model Weight=Sex Chol_Status Sex*Chol_Status / ss1 ss3;
	lsmeans Sex Chol_Status / adjust=tukey pdiff=all alpha=0.05 cl;
quit;

/*
 * The comparisons for Chol_Status were all significant different: 
 * Borderline and Desirable with (P<.0001), Borderline and High with (p=0.0204),
 * Desirable and High with (p<.0001).
 * 
 */