/*
 * 7-4
 * Use the Excel workbook Coffee_HR.xls to create a SAS data set called
 * Coffee_HR. This data set will include the variables Subj, 
 * Group (Coffee or Placebo), and HR (heart rate).
 * Conduct a two-sample t test to compare heart rates between coffee
 * and placebo groups.
 */

/* Generated Code (IMPORT) */
/* Source File: Coffee_HR.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/16/17, 6:46 PM */

%web_drop_table(WORK.Coffee_HR);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Coffee_HR.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.Coffee_HR;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Coffee_HR; RUN;


%web_open_table(WORK.Coffee_HR);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/16/17, 6:47 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

/*** Test for normality ***/
proc univariate data=WORK.COFFEE_HR normal mu0=0;
	ods select TestsForNormality;
	class Group;
	var HR;
run;

/*** t Test ***/
proc ttest data=WORK.COFFEE_HR sides=2 h0=0 plots(showh0);
	class Group;
	var HR;
run;