/*
 * 7-2
 * Using the SAS data set Diabetes from problem 6-1, compute a two-sample
 * t test that compares Glucose between the two values for the variable
 * Insulin (1=yes uses insulin, 0=does not use insulin). Add a test for
 * normality for Glucose.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/16/17, 5:09 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

/*** Test for normality ***/
proc univariate data=WORK.DIABETES normal mu0=0;
	ods select TestsForNormality;
	class Insulin;
	var Glucose;
run;

/*** t Test ***/
proc ttest data=WORK.DIABETES sides=2 h0=0 plots(showh0);
	class Insulin;
	var Glucose;
run;