/*
 * 7-3
 * You have measured the heart rate of 12 subjects before and after they
 * have each drank a cup of coffee. Create a SAS data set (call it coffee)
 * from the data either by entering it into Excel and using the Import 
 * utlity or by writing a DATA step. Then run  a paired t test comparing
 * the before and after values.
 */

/* Generated Code (IMPORT) */
/* Source File: Coffee.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/other_data */
/* Code generated on: 9/16/17, 6:33 PM */

%web_drop_table(WORK.Coffee2);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/other_data/Coffee.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.Coffee2;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Coffee2; RUN;


%web_open_table(WORK.Coffee2);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/16/17, 6:35 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

data Work._Paired_diffs_;
	set WORK.COFFEE2;
	_Difference_=After - Before;
	label _Difference_="Difference: After - Before";
run;

/*** Test for normality ***/
proc univariate data=Work._Paired_diffs_ normal mu0=0;
	ods select TestsForNormality;
	var _Difference_;
run;

/*** t Test ***/
proc ttest data=WORK.COFFEE2 sides=2 h0=0 plots(showh0);
	paired After*Before;
run;

/*** Clean up ***/
proc delete data=work._paired_diffs_;
run;

/*
 * p value of 0.0428 s.t. we do not reject H0: that the data values are 
 * distributed.normally
 */
