/*
 * 7-1
 * Using the SAS data set Diabetes from problem 6-1, compute a two-sample
 * t test that compares Glucose from two of the three Diet_Drinks values
 * (omit Diet_Drinks = 'Sometimes').   
 */

/* Generated Code (IMPORT) */
/* Source File: Diabetes.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/16/17, 4:50 PM */

%web_drop_table(WORK.Diabetes);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Diabetes.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.Diabetes;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Diabetes; RUN;


%web_open_table(WORK.Diabetes);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/16/17, 4:52 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

/*** Test for normality ***/
proc univariate data=WORK.DIABETES normal mu0=0;
	ods select TestsForNormality;
	where Diet_Drinks ne 'Sometimes';
	class Diet_Drinks;
	var Glucose;
run;

/*** t Test ***/
proc ttest data=WORK.DIABETES sides=2 h0=0 plots(showh0);
	where Diet_Drinks ne 'Sometimes';
	class Diet_Drinks;
	var Glucose;
run;

/*
 * Highly significant result with t value = 4.94 and p-value < 0.0001.
 * We note that the Glucose mean was 240.1 for the "Often" group and 
 * the Glucose mean was only 131.5 for the "Rarely" Diet_Drinks group.
 */