/*
 * 10-1
 * Start with the Excell workbook Blood_Pressure.xlsx and create a temporary
 * SAS data set called BP. Compute a Pearson and Spearman (nonparametric)
 * correlation between the two variables SBP and DBP. Select the appropriate 
 * option to print a scatter plot.
 */

/* Generated Code (IMPORT) */
/* Source File: Blood_Pressure.xlsx */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/19/17, 3:22 PM */

%web_drop_table(WORK.BP);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Blood_Pressure.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.BP;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.BP; RUN;


%web_open_table(WORK.BP);


/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/19/17, 3:41 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc corr data=WORK.BP pearson spearman nosimple plots=scatter(ellipse=none);
	var SBP DBP;
run;