/*
 * 10-3
 * Take a random sample of size 500 from SASHELP.Heart data set (use a fixed
 * seed of 13579). Call the sample Sample_Heart. Include all the variables
 * in the sample. Repeat problem 2 using the sample.Compare correlations
 * and p-valus between full data and the sample.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/19/17, 3:53 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

proc surveyselect data=SASHELP.HEART out=WORK.Sample_Heart method=srs 
		sampsize=500 seed=13579;
run;

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/19/17, 3:55 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc corr data=WORK.SAMPLE_HEART pearson nosimple plots(maxpoints=none)=matrix;
	var Height Weight Cholesterol;
run;

/*
 * Note that the coeerelations are similar with the full data set but the p-values
 * are now larger.
 */