/*
 * 10-2
 * Using the SAHELP data set Heart, compute a correlation matrix with the 
 * variables Height, Weight, and Cholesterol. Be sure to include p-values 
 * in the table. Request a matrix of scatter plots and be sure to set the
 * number of points plotted to unlimited. 
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/19/17, 3:43 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc corr data=SASHELP.HEART pearson nosimple plots(maxpoints=none)=matrix;
	var Height Weight Cholesterol;
run;