/*
 * 11-1
 * Using the data set SASHELP.Heart, run a simple linear regression with 
 * Weight as the dependent variable and Height as the independent or predictor
 * variable. Include a scatter plot of the data. Using the paramenter estimates,
 * what is the predicted weight for a person 65 inches tall? 
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/23/17, 5:31 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc reg data=SASHELP.HEART alpha=0.05 plots(only)=(diagnostics residuals 
		fitplot observedbypredicted);
	model Weight=Height /;
	run;
quit;

/*
 * From the output we use eqn weight = -117.60933 + 4.17649*height
 * st if height = 65, we have weight = 153.86 lbs.
 */


