/*
 * 11-3
 * Using the data set SASHELP.Heart, run a regresion with Weight as the 
 * dependent variable and Cholesterol, Systolic, and Sex as predictor
 * variables. Add teh option to include the VIR and omit all plots. 
 * Rerun this same model using stepwise regression. Which of the variables
 * are included in the stepwise model?
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/23/17, 6:20 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glmselect data=SASHELP.HEART outdesign(addinputvars)=Work.reg_design;
	class Sex / param=glm;
	model Weight=Systolic Diastolic Cholesterol Sex / showpvalues selection=none;
run;

proc reg data=Work.reg_design alpha=0.05 plots(only 
		maxpoints=none)=(observedbypredicted);
	where Sex is not missing;
	ods select ObservedByPredicted;
	model Weight=&_GLSMOD /;
	run;
quit;

proc delete data=Work.reg_design;
run;

ods noproctitle;
ods graphics / imagemap=on;

proc glmselect data=SASHELP.HEART outdesign(addinputvars)=Work.reg_design 
		plots=(criterionpanel);
	class Sex / param=glm;
	model Weight=Systolic Diastolic Cholesterol Sex / showpvalues 
		selection=stepwise
    
   (select=sbc);
run;


/*
 * Now with stepwise selected
 */
proc reg data=Work.reg_design alpha=0.05 plots(only 
		maxpoints=none)=(observedbypredicted);
	where Sex is not missing;
	ods select ObservedByPredicted;
	model Weight=&_GLSMOD /;
	run;
quit;

proc delete data=Work.reg_design;
run;

/*
 * Only 2 variables: Sex and Diastolic are get included into the stepwise
 * regression model.
 */