/*
 * 11-2
 * Using the data set SASHELP.Heart, run a regression with weight as the 
 * dependent variable and Cholesterol, Systolic, and Sex as predictor 
 * variables. Include a panel of diagnostic plots. Because this data set
 * contains over 5000 observations, be sure to increase the default value 
 * of 5000 for num of data points to plot. Approximately how much lighter
 * is a female than a male with the same systolic blood pressure and 
 * cholesterol? 
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/23/17, 6:04 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glmselect data=SASHELP.HEART outdesign(addinputvars)=Work.reg_design;
	class Sex / param=glm;
	model Weight=Systolic Cholesterol Sex / showpvalues selection=none;
run;

proc reg data=Work.reg_design alpha=0.05 plots(only 
		maxpoints=none)=(diagnostics residuals observedbypredicted);
	where Sex is not missing;
	ods select DiagnosticsPanel ResidualPlot ObservedByPredicted;
	model Weight=&_GLSMOD /;
	run;
quit;

proc delete data=Work.reg_design;
run;

/*
 * From the output, a female with same systolic blood pressure and 
 * cholesterol as male would be 26.4 lbs lighter.
 */