/* Solutions for Chapter 3
* Programmer: Stephen Blatti
* 09/03/2017
*/
* 3-1: Use the import Utility to create a temporary data set called Clinical 
* using the Excel workbookClinicData.xlsx.
* Use the List Data task to list the data set.

/* Generated Code (IMPORT) */
/* Source File: ClinicData.xlsx */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/3/17, 4:03 PM */

%web_drop_table(WORK.Clinic);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/ClinicData.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.Clinic;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Clinic; RUN;


%web_open_table(WORK.Clinic);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/3/17, 4:10 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

title1 "List Data for WORK.CLINIC";

proc print data=WORK.CLINIC label;
	var PtNum Visit_Date Heart_Rate Sstolic Diastolic Gender;
run;

title1;
