/*
* Programmer: Stephen Blatti
* 09/03/2017
 * 3-4:
 * Using the SAS data set Diabetes, use a filter to display all subjects with 
 * blood glucose levels (var Glucose) above 400. You can do this by creating a temp
 * SAS data set you created in prob 2 or 3, or you can ust the permanent SAS data
 * set diabetes that you downloaded to your harddrive. Refer to porb instructions 
 * section of the book if you forgot how to create a libref.
 * 
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/3/17, 5:01 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

title1 "List Data for WORK.DIABETES";

proc print data=WORK.DIABETES label;
	where Glucose > 400;
	var Subj Insulin Diet_Drinks Glucose;
run;

title1;
