/*
 * Programmer: Stephen Blatti
 * 09/07/2017
 * 5-4
 * Using the BP data set from question 5-3, compute summary statistics
 * for sbp with Drug as a classification variable. Add a request for a 
 * histogram and a comparativer box plot.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/7/17, 8:21 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc means data=WORK.BP chartype mean std min max n vardef=df;
	var SBP;
	class Drug;
run;

proc univariate data=WORK.BP vardef=df noprint;
	var SBP;
	class Drug;
	histogram SBP;
run;

proc sort data=WORK.BP out=WORK.TempSorted2236;
	by Drug;
run;

proc boxplot data=WORK.TempSorted2236;
	plot (SBP)*Drug / boxstyle=schematic;
run;

proc datasets library=WORK noprint;
	delete TempSorted2236;
	run;
