/*
 * Programmer: Stephen Blatti
 * 09/04/2017
 * 4-3
 * The file Blood_Pressure.txt is a tab-delimited file.
 * 
 * The first row does not contain column names. Also, two tabs together
 * indicate a missing value (hint DSD option). 
 * Write a DATA step to read this text file and create a temporary SAS
 * data set called Blood_Pressure. Remember that a tab is represented by
 * the Hexidecimal constant '09'x. Make sure that the length for the 
 * character variables matches the maximum length in the table from
 * the textbook. 
 * Use the list data task to list the first 10 rows of this table.
 */

data Blood_Pressure;
infile '/folders/myfolders/Biostatistcs by Example/problems/Blood_Pressure.txt'
	dlm = '09'x dsd pad;
	length Drug$ 7 Gender$ 1;
	input Drug Subj Gender SBP DBP;
run;

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/4/17, 4:57 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

title1 "List Data for WORK.BLOOD_PRESSURE";

proc print data=WORK.BLOOD_PRESSURE
	(obs=10) label;
	var Drug Gender Subj SBP DBP;
run;

title1;
