/*
 * Programmer: Stephen Blatti
 * 09/07/2017
 * 5-2
 * Using the same data set as problem 5-1, compute summary statistics 
 * for the variable T, broken down by the variable Group. Request a
 * histogram and a comparative box plot.
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/7/17, 7:54 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc means data=SASHELP.BMT chartype mean std min max n vardef=df;
	var T;
	class Group;
run;

proc univariate data=SASHELP.BMT vardef=df noprint;
	var T;
	class Group;
	histogram T;
run;

proc sort data=SASHELP.BMT out=WORK.TempSorted2236;
	by Group;
run;

proc boxplot data=WORK.TempSorted2236;
	plot (T)*Group / boxstyle=schematic;
run;

proc datasets library=WORK noprint;
	delete TempSorted2236;
	run;