/*
 * 8-5
 * Using teh SASHELP data set BMT, test if the T values are different for 
 * each of the three groups. What is the overall p-value, and which groups,
 * if any, are significantly different at 0.05 level? 
 */

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/17/17, 8:50 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

Title;
ods noproctitle;
ods graphics / imagemap=on;

proc glm data=SASHELP.BMT;
	class Group;
	model T=Group;
	means Group / hovtest=levene welch plots=none;
	lsmeans Group / adjust=tukey pdiff alpha=.05;
	run;
quit;

/*
 * The overall p-value for the test is p=0.0012. Fo All and Low we reject 
 * H_0 and conclude that there is sig difference between ALL and Low Risk (p=0.0081). 
 * And between Low and High we reject H_0 and conclude that there is a significant 
 * difference between Low and High Risk (p=0.0031)
 */