/*
 * 8-3
 * Starting with the diabetes.xls workbook, create a SAS data set called
 * Diabetes. Test if there is a relationship between between how often a
 * person drinks diet drinks and the glucose level. What is the overall
 * p-value for the ANOVA; test if there are any pairwise differences.
 * If so, what are they and what are the p-values?
 */

/* Generated Code (IMPORT) */
/* Source File: Diabetes.xls */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/17/17, 8:27 PM */

%web_drop_table(WORK.Diabetes);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Diabetes.xls';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.Diabetes;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.Diabetes; RUN;


%web_open_table(WORK.Diabetes);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/17/17, 8:29 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

Title;
ods noproctitle;
ods graphics / imagemap=on;

proc glm data=WORK.DIABETES;
	class Diet_Drinks;
	model Glucose=Diet_Drinks;
	means Diet_Drinks / hovtest=levene welch plots=none;
	lsmeans Diet_Drinks / adjust=tukey pdiff alpha=.05;
	run;
quit;

/*
 * The overall p-value for the ANOVA is P <.0001. 
 * The Tukey comparison test shows a significant difference (reject H_0)
 * between Often and Rarely with P<.0001.
 * if there are any pairwise differences.
 */