/*
 * 8-1
 * Starting with the workbook Blood_Pressure.xls, create a temporary
 * SAS data set called BP. Use this data set to perform a one-way
 * ANOVA, testing the three drugs' effects om SBP (systolic blood pressure).
 * What is the overall p-value for the test? Using the Tukey method of
 * multiple comparisons, what do you conclude about the three drug levels
 * (Placebo, Drug A, and Drug B)?  
 */

/* Generated Code (IMPORT) */
/* Source File: Blood_Pressure.xlsx */
/* Source Path: /folders/myfolders/Biostatistcs by Example/problems */
/* Code generated on: 9/17/17, 6:30 PM */

%web_drop_table(WORK.BP);


FILENAME REFFILE '/folders/myfolders/Biostatistcs by Example/problems/Blood_Pressure.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.BP;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.BP; RUN;


%web_open_table(WORK.BP);

/*
 *
 * Task code generated by SAS Studio 3.6 
 *
 * Generated on '9/17/17, 6:31 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-642.6.2.el6.x86_64' 
 * Generated on SAS version '9.04.01M4P11092016' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/36/main?locale=en_US&zone=GMT-05%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F36%2F=' 
 *
 */

Title;
ods noproctitle;
ods graphics / imagemap=on;

proc glm data=WORK.BP;
	class Drug;
	model SBP=Drug;
	means Drug / hovtest=levene welch plots=none;
	lsmeans Drug / adjust=tukey pdiff alpha=.05;
	run;
quit;


/*
 * The overall p-value for the test 0.0197. The Tukey test shows p-value 
 * of 0.0077 for the test between placebo and Drug B so that we reject
 * H_0 and conclude that Drug B and placebo are significantly different.
 */